name = "Project3"
uuid = "a87ea0c4-effc-4c39-b324-814a8a71756c"
version = "0.1.0"
authors = [
  # use one line per author to ease conflict resolution
  "Rishi Ram <rishi.ram@stud.klu.org>",
  "Arth Gupta <arth.gupta@stud.klu.org>",
  "Mirah Semarandhanu <mirah.semarandhanu@stud.klu.org>",
  "Rishi Harpreet Singh Jagdev <rishi.jagdev@stud.klu.org>",
  "Valeria Rendon Corredor <valeria.rendoncorredor@stud.klu.org>"
]


[workspace]
projects = ["docs", "test"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
Mongoc = "4fe8b98c-fc19-5c23-8ec2-168ff83495f2"

[compat]
DotEnv = "1.0.0"
Mongoc = "0.10.1"
julia = "1.12"
